### ISSUE TITLE
Current Build Triggers Deprecation Warning

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s.g8#10]
Current server utilizes `.awaitShutdown()` and has been deprecated since `0.14` recommendation is `ServerApp`. Is this a transition we would like the template to make?

**Comment by rossabaker** [comment]
I want to deprecate `ServerApp` in favor of a `ProcessApp` that I'm working on open sourcing, but `ServerApp` _is_ the best thing going right now.  So, :+1:, but it won't be long lived.

**Comment by ChristopherDavenport** [comment]
Closed By #11
