### ISSUE TITLE
Enabling sbt-tpolecat plugin reveals tons of unused imports

### ISSUE THREAD

**Issue by hejfelix** [http4s/http4s.g8#103]
Maybe the template requires some cleanup?

**Comment by rossabaker** [comment]
Do any of those unused imports inevitably become used when someone builds a non-trivial service?  Since it already is a "real" service, I'm inclined to say no, and we should clean them up.

**Comment by hejfelix** [comment]
Didn't really get an overview. Looked like it simply hadn't been cleaned up.
