### ISSUE TITLE
Seems to be wrong implicit

### ISSUE THREAD

**Issue by declspec-cdecl** [http4s/http4s.g8#108]
Threre is code chunk at line [14](https://github.com/http4s/http4s.g8/blob/a2d38fa92506bc157547267ffca5d8a7a4f47f9e/src/main/g8/src/main/scala/%24package__packaged%24/HelloWorld.scala#L14) in HelloWorld.scala that looks wrong.

**Comment by rossabaker** [comment]
What is wrong about it?  It looks like the "summoner" pattern, enabling syntax `HelloWorld[F]` to summon an instance of `HelloWorld[F]`.  I might also be looking at it wrong. :smile:

**Comment by SystemFw** [comment]
it shouldn't be `implicit def apply`, just `def apply`

**Comment by declspec-cdecl** [comment]
> it shouldn't be `implicit def apply`, just `def apply`

Yep, thats right. It looks like the summoner is not used. It is not a big problem but it might be confusing for newbies

**Comment by rossabaker** [comment]
Oh, right.  Most implementations will come from `impl`, so the summoner is of questionable utility.  I could go either for removing the summoner or making it not implicit.

**Comment by declspec-cdecl** [comment]
I think all alternative has their pros and cons. But if this is never used at generated demo then better to minimize codebase.

**Comment by reardonj** [comment]
I'm planning to do fixes for #278, so I may as well fix this too. It sounds like deleting the `implicit def` is an acceptable solution?
