### ISSUE TITLE
Github action CI / GraalVM broke on merge into .21

### ISSUE THREAD

**Issue by apple-corps** [http4s/http4s.g8#148]
After https://github.com/drocsid/http4s.g8/tree/feature/github-actions had merged we had unexpected CI failures for building the native-image.For example https://github.com/drocsid/http4s.g8/runs/707353485?check_suite_focus=true#step:7:187 passed but https://github.com/http4s/http4s.g8/runs/756302615?check_suite_focus=true#step:7:309 failed.

Furthermore re-running actions that passed previously in https://github.com/drocsid/http4s.g8/tree/feature/github-actions resulted in failures.

Finally my local graalvm native image build is working. Since we should be building against static deployment artifacts (http4s .21 released, etc) and not master versions then possibly something from https://github.com/olafurpg/setup-scala , https://www.graalvm.org/ , or https://github.com/features/actions is causing the issue.

**Comment by apple-corps** [comment]
Here's the output from my local build. Still behind graal version locally: https://gist.github.com/drocsid/9f5329cd2e10d7454172fd8de2a68adf

**Comment by apple-corps** [comment]
Graal building locally against latest version: https://gist.github.com/drocsid/5cf1fe1498f01f068ce183d00fc1d624

**Comment by apple-corps** [comment]
Looks like jabba used by #setup-scala changed the naming convention for their graalvm builds and it was trying to build against jdk8 which doesn't work well... Sheesh.

**Comment by apple-corps** [comment]
https://github.com/shyiko/jabba/commit/552b2cc9c9936e9630ff895e418deaae9c705fc2

**Comment by drocsid** [comment]
https://github.com/olafurpg/setup-scala/issues/21

**Comment by apple-corps** [comment]
Please merge #149

**Comment by rossabaker** [comment]
Fixed by #149.
