### ISSUE TITLE
`BlazeServerBuilder` uses deprecated version of `apply`

### ISSUE THREAD

**Issue by alexandervanhecke** [http4s/http4s.g8#150]
Hi, I just instantiated the https g8 using the following parameters : 
- scala 2.13.2
- sbt 1.3.10
- http4s 0.21.4
- circe 0.13.0

(default values for other parameters)

this does not compile out of the box for me because the `BlazeServerBuilder` uses the `apply` method without parameters.  That version is deprecated, which results in a compile error.

This is easily fixed by using the `apply` method that takes an `ExecutionContext` as a parameter, ie 

`BlazeServerBuilder[F](ExecutionContext.global)`

Let me know if you want me to provide a PR.

**Comment by ChristopherDavenport** [comment]
PR super appreciated.
