### ISSUE TITLE
Old version of sbt-tpolecat causes error on new project

### ISSUE THREAD

**Issue by amaalali** [http4s/http4s.g8#175]
When `sbt-tpolecat` is enabled on a new project, the following error is generated.

```
[error] bad option: '-Yno-adapted-args'
```

This option has been removed and this is been updated in newer version of `sbt-tpolecat`.

Updating the library to it's newest version should fix this issue.

**Comment by rossabaker** [comment]
Thanks.  I've tried to address this in #176.
