### ISSUE TITLE
Missing resolver for scalaz-stream

### ISSUE THREAD

**Issue by trepidacious** [http4s/http4s.g8#2]
As set up, my project based on this template wouldn't run due to failure to find scalaz-stream, I added this to build.sbt and it worked:

resolvers += "Scalaz Bintray Repo" at "https://dl.bintray.com/scalaz/releases"

Presumably if dependencies of http4s are updated, this will not be necessary since scalaz-stream is now on maven central? I'm using http4s 0.8.4, which seems to be the most recent?

**Comment by rossabaker** [comment]
http4s-0.9.1 depends on a version of scalaz-stream that is now on Maven Central.  This should no longer be necessary.
