### ISSUE TITLE
Reinstate stable versions when `sbt new` supports it

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s.g8#25]
@ChristopherDavenport did really nice work with the `maven(org.http4s, http4s-blaze-server_2.12, stable)` syntax, but it doesn't work on Giter8 0.7.2, which is what comes bundled with sbt.  I commented these out, because `sbt new` is the lowest friction way for new users to try us out, but I really want to go back to this feature.

Blocked by https://github.com/sbt/sbt-giter8-resolver/pull/8

**Comment by froth** [comment]
I first did this in #324 but letting Scala Steward handle the  updates seems preferable. I will close this when the PR is merged.
