### ISSUE TITLE
Explore giter8 0.10's support for conditionals

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s.g8#26]
We've got three active branches right now referenced from the documentation.  One of them has already diverged from the other two beyond dependency differences.  Can we use conditionals to maintain one branch, in a loving tribute to the late Yax?

/cc @ChristopherDavenport 

Blocked by https://github.com/sbt/sbt-giter8-resolver/pull/8

**Comment by ChristopherDavenport** [comment]
I'm moving towards centralizing on 0.18.0 or whatever our recommended starting option is rather than branching. This was relevant when we were in between branches. Which I feel we are not anymore.

**Comment by rossabaker** [comment]
I'm fine with that. Rho was the last major reason for 0.17, and most of our
0.16 users aren't new.

**Comment by ChristopherDavenport** [comment]
Closing Since we are centralizing on 0.18. We may bring back master on 0.18 final release but for the time being what he have is sufficient until we make a new move.
