### ISSUE TITLE
Why is the template based on `Stream`?

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s.g8#278]
Specifically this part:

https://github.com/http4s/http4s.g8/blob/413274b75511156e1229174e382f2b966cde74ff/src/main/g8/src/main/scala/%24package__packaged%24/%24name__Camel%24Server.scala#L14

Seems like a vanilla `Resource` would work just fine via `useForever` instead of this thing:
https://github.com/http4s/http4s.g8/blob/413274b75511156e1229174e382f2b966cde74ff/src/main/g8/src/main/scala/%24package__packaged%24/%24name__Camel%24Server.scala#L38

Motivation: just got a question about this on the Discord. IMO `Stream` is a very big step up from `IO` and `Resource` for a newcomer.

**Comment by armanbilge** [comment]
Interestingly, the `IO` version of the template uses `Resource` and `useForever` exactly like what you would expect.
https://github.com/http4s/http4s-io.g8/blob/66150a467f6a046ff40e2fca6fd65de2fe3c6e7e/src/main/g8/src/main/scala/$package__packaged$/$name__Camel$Server.scala

If this is meant to be an "advanced" template, maybe we should make the distinction more clear?

**Comment by rossabaker** [comment]
I would say legacy.  `StreamApp` predates `IOApp`.  I've been trying to teach at work that a `Stream[F, ExitCode]` is almost never what you want.

**Comment by reardonj** [comment]
I'm going to fix this template to use `Resource` and `useForever` like the other one.
