### ISSUE TITLE
Test our template

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s.g8#28]
We should be testing our templates.  It gives a terrible first impression when a project template doesn't work.  It should be possible to set up our templates under Travis.

The [Giter8 plugin](http://www.foundweekends.org/giter8/testing.html#Using+the+Giter8Plugin) supports this.

/cc @ChristopherDavenport, who has expressed this before

**Comment by ChristopherDavenport** [comment]
Didn't we gain this on merging my features?

**Comment by rossabaker** [comment]
I think partially.  The plugin is there and running the tests, but I don't see any tests.  Can we validate that the project materializes and compiles?

**Comment by ChristopherDavenport** [comment]
#34 Seems a definitive test of this,

**Comment by rossabaker** [comment]
Oh, neat.  I don't yet understand how it works, but neat!  Yeah, I think we're good here, then.
