### ISSUE TITLE
Template should include tests

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s.g8#29]
Our generated template should include unit tests so people have some idea how to test their service.

**Comment by bneil** [comment]
PR here https://github.com/http4s/http4s.g8/pull/44

**Comment by bneil** [comment]
Are we waiting on anything else for that PR to be merged?

**Comment by rossabaker** [comment]
Sorry, I fell behind.  I just responded on the multiple `unsafeRun`s.  Let me know what you think, but I think we're real close.  (In fact, #44 is already unambiguously forward progress.)

**Comment by ChristopherDavenport** [comment]
Closed By #44 - One Route, Tests 1 Route.
