### ISSUE TITLE
org.http4s#http4s-blaze-server_2.12.0-M3;0.10.1: not found

### ISSUE THREAD

**Issue by nicl** [http4s/http4s.g8#6]
The Blaze dependency isn't on Maven (from what I can see) for Scala 12. Shifting to using an 11 version works fine, so might be worth keeping the g8 default Scala version to 11 for now.

(This is a very minor complaint though!)

**Comment by rossabaker** [comment]
Good idea. It's a floating version in the template, and it floated too high.

**Comment by bfritz** [comment]
Pretty sure this is fixed as http4s-blaze-server [is published for 2.12](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.http4s%22%20AND%20a%3A%22http4s-blaze-server_2.12%22) now.

Just ran:
```
sbt -sbt-version 0.13.13 new http4s/http4s.g8
```

and selected defaults including `scala_version [2.12.1]:`.  Afterward:

```
sbt run
```

resolved deps and started the example server without issue.

**Comment by ChristopherDavenport** [comment]
Yes, recent commits should have resolved this issue. If not please make further comments and we will reopen. Closing for now.
